---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  shell: |
    npm install pm2 -g && pm2 update
    pm2 completion install