---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  shell: |
    apt install curl
    curl -sL https://deb.nodesource.com/setup_17.x -o /tmp/nodesource_setup.sh
    bash /tmp/nodesource_setup.sh
    apt install nodejs
    apt install build-essential

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present