---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    version: '17.3.0'
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present