- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: extract the zipped artifact into the EC2 instance
  template:
    src: "backend/"
    dest: "~/web/"

- name: Executing node
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start