- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: move the zipped artifact into the EC2 instance
  template:
    src: "files/'artifact.tar.gz'"
    dest: "~/web/"

# - name: Install tar utility
#   command: |
#     sudo apt-get update
#     sudo apt-get install tar -y

- name: Executing node
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start