- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: move the zipped artifact into the EC2 instance
  unarchive:
    src: "artifact.tar.gz"
    dest: "~/web/"

- name: Executing node
  shell: |
    cd web/backend
    npm install
    pm2 stop default
    pm2 start npm -- start