- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: move the zipped artifact into the EC2 instance
  unarchive:
    src: "artifact.tar.gz"
    dest: "~/web/"

- name: Executing node
  shell: |
    cd ~/web
    npm install
    # npm run build
    cd ~/web/dist
    pm2 stop default
    # pm2 start npm -- start
    pm2 start main.js
  register: execute_node

- name:
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu